# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_to_product', models.DecimalField(decimal_places=5, max_digits=15)),
                ('qty_needed', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredienti',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Scaffale',
                'verbose_name_plural': 'Scaffali',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fasi',
            },
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('readable_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Unità di misura',
                'verbose_name_plural': 'Unità di misura',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
            options={
                'verbose_name': 'Magazzino',
                'verbose_name_plural': 'Magazzini',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Product')),
                ('complete_meal', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Product')),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ricetta',
                'verbose_name_plural': 'Ricette',
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Product'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Shelf'),
        ),
        migrations.AddField(
            model_name='step',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.UoM'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Step'),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe'),
        ),
        migrations.AddField(
            model_name='menu',
            name='courses',
            field=models.ManyToManyField(to='core.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('number', 'recipe')]),
        ),
    ]
