# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 10:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_warehouse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='qty_needed',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='qty_to_product',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
