# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170610_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithRecipe',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='step',
        ),
        migrations.AlterField(
            model_name='course',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.ProductWithRecipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.ProductWithRecipe'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
