# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170610_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='productwithrecipe',
            options={'verbose_name': 'Prodotto con ricetta', 'verbose_name_plural': 'Prodotti con ricetta'},
        ),
        migrations.AddField(
            model_name='productwithrecipe',
            name='is_complete_meal',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='productwithrecipe',
            name='is_course',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='courses',
            field=models.ManyToManyField(to='core.ProductWithRecipe'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
