# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170610_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='step',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='step',
            name='result',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
