# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170610_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_to_product', models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty_needed', models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Inredienti',
            },
        ),
        migrations.RemoveField(
            model_name='productwithrecipe',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_complete_meal',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.SmallIntegerField(choices=[(3, 'Piatto'), (2, 'Preparato'), (3, 'Piatto')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='courses',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Product'),
        ),
        migrations.DeleteModel(
            name='ProductWithRecipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='receipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set([('product', 'receipe', 'qty_to_product')]),
        ),
    ]
