# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170616_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredienti'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='receipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'Piatto'), (2, 'Preparato'), (3, 'Materia prima')]),
        ),
    ]
